FROM oven/bun:alpine

WORKDIR /app

COPY app/package.json app/bun.lock ./
RUN bun install --production --frozen-lockfile && apk add --no-cache curl

COPY app/src ./src

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=5 \
  CMD curl -f http://localhost:3000/health || exit 1

USER bun
CMD ["bun", "run", "run:prod"]