networks:
  gitea:
    external: false

services:
  app:
    build:
      context: ..
      dockerfile: lab/containerfile
    container_name: app
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  repository:
    image: docker.gitea.com/gitea:1.27.3
    container_name: repository
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone.ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8000"
      - "222:22"

